### ISSUE TITLE
Collaborating on iteration of `Hidden Bias` with tfjs models

### ISSUE THREAD

**Issue by kevinrobinson** [PAIR-code/ai-explorables#2]
hi @1wheel!  Thanks for sharing this work in the open 😄 

I was poking around with this and noticed that the data is simulated, but the model predictions are described in code rather than learned.  Any interest in collaborating on an iteration to generate simulated data, then drop in TensorFlow.js to train the series of models that can illustrate the points in the piece?

I've hacked around on this, tangled up with some other changes that highlight the differences in cohorts (eg, students who applied, enrolled, and completed their first year vs. applicants).  If you're up for it, I could share a branch as a starting point for seeing if there's anything in there you'd find interesting to collaborate on.  If this seems super awesome, we could figure out how it becomes an extension to the original post, and if not no worries, and thanks for sharing in the open! 👍

**Comment by 1wheel** [comment]
Interesting idea! I didn't want to try and explain overfitting, so I stuck with the hard coded the correlations.

I'm a little too crunched on time right now to start work on an extension (when will the daycares reopen??), but happy to drop in a link if you publish something!
